packages:
  - apps/*
  - packages/*
overrides:
  '@prisma/dev>@hono/node-server': 1.19.13
  concurrently>shell-quote: 1.8.4
  miniflare>ws: 8.20.1
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: true
  workerd: true
