packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: true
  workerd: true
