packages:
  - apps/*
  - packages/*
overrides:
  '@prisma/config>deepmerge-ts': 8.0.0
  'prisma>mysql2': 3.24.4
  'miniflare>undici': 7.29.1
  '@nestjs/swagger>js-yaml': 5.4.3
  'miniflare>sharp': 0.35.5
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: true
  workerd: true
