export enum ErrorCode {
  SYSTEM_BAD_REQUEST = 'SYSTEM_BAD_REQUEST',
  SYSTEM_UNAUTHORIZED = 'SYSTEM_UNAUTHORIZED',
  SYSTEM_FORBIDDEN = 'SYSTEM_FORBIDDEN',
  SYSTEM_NOT_FOUND = 'SYSTEM_NOT_FOUND',
  SYSTEM_CONFLICT = 'SYSTEM_CONFLICT',
  SYSTEM_INTERNAL_SERVER_ERROR = 'SYSTEM_INTERNAL_SERVER_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
}
