name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm run test

  build:
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest
    env:
      VITE_PROXY_API_BASE_URL: ${{ vars.VITE_PROXY_API_BASE_URL }}
      VITE_GA_ID: ${{ vars.VITE_GA_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - uses: actions/configure-pages@v5
      - run: pnpm run build
      - run: cp build/client/index.html build/client/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
